#!/bin/bash
set -e

SCRIPT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_HOME/../dev.env fast

pushd $APP_ROOT/src > /dev/null
TEST_DIRS=$(find . -type f -name test.js | sed 's|/test.js||g' | xargs ls -1dt)
popd > /dev/null

echo $TEST_DIRS                           | \
	tr " " "\n"                       | \
	sed 's|^.|http://localhost:2001|' | \
	sed 's|$|/test.html|'             | \
	parallel --halt 2 "test-single-js {}"
